FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libffi-dev \
    python3-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY simulate_weather.py /app/
COPY producer.py /app/

RUN pip install confluent-kafka

CMD ["python", "simulate_weather.py"]
