services:
  kafka:
    image: apache/kafka
    container_name: kafka_dbt
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - weather-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=weather_monitoring
    ports:
      - "3307:3306"
    volumes:
      - mysql_dbt_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - weather-network

  json-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: json-server
    ports:
      - "3000:3000"
    networks:
      - weather-network
      
  spark:
    image: bitnami/spark:3.4.1
    container_name: spark
    user: root
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./spark:/opt/spark
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge

volumes:
  mysql_dbt_data:
